version: "3.8"
services:
  web:
    build: .
    command: gunicorn -w 2 -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app # remove in production
    restart: unless-stopped
